from fastapi import APIRouter

from app.api.v1.endpoints import academic_calendar_settings, academic_years, analytics, attendance_staff, attendance_students, audit_logs, auth, backup, batch, certificates, classes, communication_logs, curriculum, discounts, documents, enrollments, events, exam_schedules, exams, online_exams, fee_dues, fee_payments, fee_structures, grades, guardians, health, holidays, import_export, leaves, library_books, library_issues, logistics, marks, messages, notices, notifications, parent_portal, payroll, reports, results, roles, schools, sections, settings, staff, staff_extended, staff_leave, streams, students, subject_groups, subjects, teacher_assignments, terms, time_slots, timetable, transport_assignments, transport_route_stops, transport_routes, transport_vehicles, users

api_router = APIRouter()
api_router.include_router(health.router, tags=["health"])
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(schools.router, prefix="/schools", tags=["schools"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(roles.router, prefix="/roles", tags=["roles"])
api_router.include_router(academic_years.router, prefix="/academic-years", tags=["academic-years"])
api_router.include_router(terms.router, prefix="/terms", tags=["terms"])
api_router.include_router(classes.router, prefix="/classes", tags=["classes"])
api_router.include_router(sections.router, prefix="/sections", tags=["sections"])
api_router.include_router(streams.router, prefix="/streams", tags=["streams"])
api_router.include_router(subject_groups.router, prefix="/subject-groups", tags=["subject-groups"])
api_router.include_router(subjects.router, prefix="/subjects", tags=["subjects"])
api_router.include_router(curriculum.router, prefix="/curriculum", tags=["curriculum"])
api_router.include_router(academic_calendar_settings.router, prefix="/academic-calendar", tags=["academic-calendar"])
api_router.include_router(students.router, prefix="/students", tags=["students"])
api_router.include_router(enrollments.router, prefix="/enrollments", tags=["enrollments"])
api_router.include_router(guardians.router, prefix="/guardians", tags=["guardians"])
# Staff routers - ORDER MATTERS! Extended routes must come before the base staff router
# to prevent /{staff_id} from matching paths like /departments
api_router.include_router(staff_extended.router, prefix="/staff", tags=["staff-extended"])
api_router.include_router(staff_leave.router, prefix="/staff", tags=["staff-leave"])
api_router.include_router(payroll.router, prefix="/staff", tags=["payroll"])
api_router.include_router(staff.router, prefix="/staff", tags=["staff"])
api_router.include_router(teacher_assignments.router, prefix="/teacher-assignments", tags=["teacher-assignments"])
api_router.include_router(attendance_students.router, prefix="/attendance/students", tags=["attendance-students"])
api_router.include_router(attendance_staff.router, prefix="/attendance/staff", tags=["attendance-staff"])
api_router.include_router(leaves.router, prefix="/leaves", tags=["leaves"])
api_router.include_router(timetable.router, prefix="/timetable", tags=["timetable"])
api_router.include_router(time_slots.router, prefix="/time-slots", tags=["time-slots"])
api_router.include_router(exams.router, prefix="/exams", tags=["exams"])
api_router.include_router(exam_schedules.router, prefix="/exam-schedules", tags=["exam-schedules"])
api_router.include_router(online_exams.router, prefix="/online-exams", tags=["online-exams"])
api_router.include_router(marks.router, prefix="/marks", tags=["marks"])
api_router.include_router(results.router, prefix="/results", tags=["results"])
api_router.include_router(grades.router, prefix="/grades", tags=["grades"])
api_router.include_router(fee_structures.router, prefix="/fee-structures", tags=["fee-structures"])
api_router.include_router(fee_payments.router, prefix="/fee-payments", tags=["fee-payments"])
api_router.include_router(fee_dues.router, prefix="/fee-dues", tags=["fee-dues"])
api_router.include_router(discounts.router, prefix="/discounts", tags=["discounts"])
api_router.include_router(notices.router, prefix="/notices", tags=["notices"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(messages.router, prefix="/messages", tags=["messages"])
api_router.include_router(communication_logs.router, prefix="/communication-logs", tags=["communication-logs"])
api_router.include_router(library_books.router, prefix="/library/books", tags=["library-books"])
api_router.include_router(library_issues.router, prefix="/library/issues", tags=["library-issues"])
api_router.include_router(transport_vehicles.router, prefix="/transport/vehicles", tags=["transport-vehicles"])
api_router.include_router(transport_routes.router, prefix="/transport/routes", tags=["transport-routes"])
api_router.include_router(transport_route_stops.router, prefix="/transport/route-stops", tags=["transport-route-stops"])
api_router.include_router(transport_assignments.router, prefix="/transport/student-assignments", tags=["transport-assignments"])
api_router.include_router(reports.router, prefix="/reports", tags=["reports"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["analytics"])
api_router.include_router(parent_portal.router, prefix="/parent", tags=["parent-portal"])
api_router.include_router(documents.router, prefix="/documents", tags=["documents"])
api_router.include_router(certificates.router, prefix="/certificates", tags=["certificates"])
api_router.include_router(events.router, prefix="/events", tags=["events"])
api_router.include_router(holidays.router, prefix="/holidays", tags=["holidays"])
api_router.include_router(settings.router, prefix="/settings", tags=["settings"])
api_router.include_router(backup.router, prefix="/backup", tags=["backup"])
api_router.include_router(import_export.router, prefix="/import-export", tags=["import-export"])
api_router.include_router(batch.router, prefix="/batch", tags=["batch"])
api_router.include_router(logistics.router, prefix="/logistics", tags=["logistics"])

