from app.db.session import Base

from app.models.membership import Membership
from app.models.refresh_token import RefreshToken
from app.models.role import Role
from app.models.academic_year import AcademicYear
from app.models.class_subject import ClassSubject
from app.models.enrollment import Enrollment
from app.models.guardian import Guardian
from app.models.school import School
from app.models.school_class import SchoolClass
from app.models.section import Section
from app.models.staff import Staff
from app.models.student import Student
from app.models.student_guardian import StudentGuardian
from app.models.subject import Subject
from app.models.stream import Stream
from app.models.subject_group import SubjectGroup
from app.models.term import Term
from app.models.curriculum_unit import CurriculumUnit
from app.models.academic_calendar_settings import AcademicCalendarSettings
from app.models.teacher_assignment import StaffAttendance, StudentAttendance, TeacherAssignment
from app.models.leave import Leave
from app.models.time_slot import TimeSlot
from app.models.timetable_entry import TimetableEntry
from app.models.exam import Exam
from app.models.exam_schedule import ExamSchedule
from app.models.grade import Grade
from app.models.mark import Mark
from app.models.result import Result
from app.models.password_reset_token import PasswordResetToken
from app.models.discount import Discount
from app.models.fee_due import FeeDue
from app.models.fee_payment import FeePayment
from app.models.fee_structure import FeeStructure
from app.models.student_discount import StudentDiscount
from app.models.notice import Notice
from app.models.notification import Notification
from app.models.message import Message
from app.models.communication_log import CommunicationLog
from app.models.library_book import LibraryBook
from app.models.library_issue import LibraryIssue
from app.models.transport_assignment import StudentTransportAssignment
from app.models.transport_route import TransportRoute
from app.models.transport_route_stop import TransportRouteStop
from app.models.transport_vehicle import TransportVehicle
from app.models.document import Document
from app.models.audit_log import AuditLog
from app.models.user_preference import UserPreference
from app.models.certificate import Certificate, CertificateTemplate
from app.models.event import Event
from app.models.holiday import Holiday
from app.models.setting import Setting
from app.models.backup_entry import BackupEntry
from app.models.attendance_excuse import AttendanceExcuse
from app.models.discipline_record import DisciplineRecord
from app.models.appointment_request import AppointmentRequest
from app.models.user import User
