"""add_tenancy_support

Revision ID: b60b1bae775e
Revises: 0031_add_contract_allowances
Create Date: 2026-01-29 01:02:58.132351

"""

from alembic import op
import sqlalchemy as sa


revision = 'b60b1bae775e'
down_revision = '0031_add_contract_allowances'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_custom_domain'), ['custom_domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenants_subdomain'), ['subdomain'], unique=True)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_classes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_classes_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_schools_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_schools_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_staff_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_staff_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('staff_performance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_staff_performance_records_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_staff_performance_records_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('staff_qualifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_staff_qualifications_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_staff_qualifications_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_students_tenant_id', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_users_tenant_id', 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('staff_qualifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_staff_qualifications_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_staff_qualifications_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('staff_performance_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_staff_performance_records_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_staff_performance_records_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint('fk_staff_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_staff_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_constraint('fk_schools_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_schools_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_classes_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_classes_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_subdomain'))
        batch_op.drop_index(batch_op.f('ix_tenants_custom_domain'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
